name: New School Backend CI

on:
  push:
    branches:
      - feature/*
      - fix/*
      - hotfix/*

  pull_request:
    branches:
      - develop

jobs:
  #integration-tests:
    #name: Integration Tests
    #runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #node-version: [12.x, 14.x]
    #steps:
      #- name: Checkout Repo
        #uses: actions/checkout@master
      #- name: Use Node.js ${{ matrix.node-version }}
        #uses: actions/setup-node@v1
        #with:
          #node-version: ${{ matrix.node-version }}
      #- name: Install Dependencies
        #run: npm ci
      #- name: Setup integration database
        #uses: mirromutth/mysql-action@v1.1
        #with:
          #mysql version: 5.7
          #mysql database: 'newschool_tests'
          #mysql user: 'newschool_tests' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          #mysql password: '123987' # Required if "mysql user" exists. The password for the "mysql user"
      #- name: Integration tests
        #run: npm run test:e2e
        #env:
          #CI: true
          #NODE_ENV: 'TEST'
          #DATABASE_HOST: 'localhost'
          #DATABASE_NAME: 'newschool_tests'
          #DATABASE_USERNAME: 'newschool_tests'
          #DATABASE_PASSWORD: '123987'
          #DATABASE_PORT: 3306

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
